################################################################################
##                             Network interface                              ##
################################################################################
server:
  # Address to which we bind (default: 127.0.0.1)
  address: "0.0.0.0"
  # Port on which we bind (default: 3836)
  port: 3836
  # Private port on which we bind (default: 4836)
  private_port: 4836
  # Endpoint of Agora
  agora_endpoint: http://127.1.1.1:4567

  #Votera required
  require_votera: true

################################################################################
##                               Database options                             ##
################################################################################
database:
   host : 127.0.0.1
   user : root
   database : devstoa
   password : "12345678"
   port : 3306
   waitForConnections : true
   connectionLimit : 10
   queueLimit : 0

################################################################################
##                               Logging options                              ##
################################################################################
logging:
  # The name of the folder where the logs are stored.
  folder: logs/
  # Values: error, warn, info, http, verbose, debug, silly
  level: http
  # Default to false
  console: true
  # Default to false
  database: true
  # Connection string for mongodb
  mongodb_url: "mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false"


################################################################################
##                               Consensus config                             ##
################################################################################
consensus:
  # 2021-01-01:00:00:00 GMT
  genesis_timestamp: 1609459200

  # The cycle length for a validator
  validator_cycle: 20

################################################################################
##                               Votrea server config                         ##
################################################################################
votera:
    # Address to which we bind (default: 127.0.0.1)
    address: "127.0.0.1"

    # Port on which we bind (default: 3836)
    port: 1337

    # Endpoint of Agora
    votera_endpoint: http://dev-votera.bosagora.com:1337/
    